version: '3.8'
services:
  DB:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=springdb
    ports:
      - '5432:5432'