version: '3.8'
services:
  API:
    image: 'spring-api-docker.jar'
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - DB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://DB:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  DB:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=springdb